apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: OAuth
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{},"name":"cluster"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpass-secret"}},"mappingMethod":"claim","name":"developer","type":"HTPasswd"}],"templates":{"login":{"name":"login-template"}},"tokenConfig":{"accessTokenMaxAgeSeconds":0}}}
      release.openshift.io/create-only: "true"
    creationTimestamp: "2021-08-10T05:01:48Z"
    generation: 2
    name: cluster
    resourceVersion: "21771"
    uid: d7c8d29a-a496-472e-8e6c-4f8b8229c2ec
  spec:
    identityProviders:
    - htpasswd:
        fileData:
          name: localusers
      mappingMethod: claim
      name: developer
      type: HTPasswd
    templates:
      login:
        name: login-template
    tokenConfig:
      accessTokenMaxAgeSeconds: 0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
